package com.cashbee.domain.model;

import com.cashbee.domain.enums.CashbackStatus;
import lombok.Builder;
import lombok.Getter;
import lombok.ToString;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * Cashback Domain Model (Pure Domain Entity - NO JPA).
 *
 * Business Purpose:
 * Represents cashback earned by user from affiliate orders.
 * Tracks the commission from platform and the cashback amount returned to user.
 *
 * Design:
 * - Immutable: All fields are final
 * - No JPA annotations: Pure domain model
 * - Self-validating: validate() method enforces business rules
 *
 * Cashback Flow:
 * 1. Order imported → Create Cashback with status PENDING
 * 2. Order completed → Update status to CONFIRMED
 * 3. Cashback added to wallet → Update status to PAID
 * 4. Order cancelled → Update status to CANCELLED
 *
 * Cashback Statuses:
 * - PENDING: Waiting for order completion
 * - CONFIRMED: Order completed, eligible for payout
 * - PAID: Cashback added to user wallet
 * - CANCELLED: Order cancelled, cashback void
 * - EXPIRED: Cashback expired (not claimed within time limit)
 *
 * @author CashBee Team
 */
@Getter
@Builder
@ToString
public class Cashback {

    /**
     * Cashback ID (generated by database).
     */
    private final Long id;

    /**
     * User who earned this cashback (FK to User).
     */
    private final Long userId;

    /**
     * Order that generated this cashback (FK to AffiliateOrder).
     * @deprecated Use orderItemId instead. Kept for backward compatibility.
     */
    private final Long orderId;

    /**
     * Order item that generated this cashback (FK to AffiliateOrderItem).
     * Each item has its own cashback record.
     */
    private final Long orderItemId;

    /**
     * Platform where order was placed (FK to AffiliatePlatform).
     */
    private final Long platformId;

    /**
     * Original commission amount from platform (VND).
     * This is the commission we earn from Shopee/Lazada.
     */
    private final BigDecimal commissionAmount;

    /**
     * Cashback amount to return to user (VND).
     * This is calculated based on cashback policy.
     * Example: If commission = 1000 and policy rate = 70%, cashback = 700
     */
    private final BigDecimal cashbackAmount;

    /**
     * Cashback rate applied (percentage).
     * Example: 70.00 means 70% of commission returned to user
     */
    private final BigDecimal cashbackRate;

    /**
     * Policy used for calculation (FK to CashbackPolicy).
     * Can be null if using default rate.
     */
    private final Long policyId;

    /**
     * Cashback status (PENDING, CONFIRMED, PAID, CANCELLED, EXPIRED).
     */
    private final CashbackStatus status;

    /**
     * Note or reason for status change.
     * Example: "Order cancelled by customer", "Expired after 90 days"
     */
    private final String note;

    /**
     * When cashback was created (usually when order imported).
     */
    private final LocalDateTime createdAt;

    /**
     * When order was confirmed (status → CONFIRMED).
     */
    private final LocalDateTime confirmedAt;

    /**
     * When cashback was paid to wallet (status → PAID).
     */
    private final LocalDateTime paidAt;

    /**
     * When cashback was cancelled (status → CANCELLED).
     */
    private final LocalDateTime cancelledAt;

    /**
     * Last update time.
     */
    private final LocalDateTime updatedAt;

    /**
     * Validate business rules.
     *
     * @throws IllegalArgumentException if validation fails
     */
    public void validate() {
        if (userId == null || userId <= 0) {
            throw new IllegalArgumentException("User ID must be positive");
        }

        if (orderId == null || orderId <= 0) {
            throw new IllegalArgumentException("Order ID must be positive");
        }

        if (platformId == null || platformId <= 0) {
            throw new IllegalArgumentException("Platform ID must be positive");
        }

        if (commissionAmount == null || commissionAmount.compareTo(BigDecimal.ZERO) < 0) {
            throw new IllegalArgumentException("Commission amount must be non-negative");
        }

        if (cashbackAmount == null || cashbackAmount.compareTo(BigDecimal.ZERO) < 0) {
            throw new IllegalArgumentException("Cashback amount must be non-negative");
        }

        if (cashbackRate == null || cashbackRate.compareTo(BigDecimal.ZERO) < 0 ||
            cashbackRate.compareTo(new BigDecimal("100")) > 0) {
            throw new IllegalArgumentException("Cashback rate must be between 0 and 100");
        }

        if (status == null) {
            throw new IllegalArgumentException("Status is required");
        }
    }

    /**
     * Check if cashback is pending (waiting for order completion).
     */
    public boolean isPending() {
        return CashbackStatus.PENDING.equals(status);
    }

    /**
     * Check if cashback is confirmed (order completed, ready to pay).
     */
    public boolean isConfirmed() {
        return CashbackStatus.CONFIRMED.equals(status);
    }

    /**
     * Check if cashback is paid (already added to wallet).
     */
    public boolean isPaid() {
        return CashbackStatus.PAID.equals(status);
    }

    /**
     * Check if cashback is cancelled.
     */
    public boolean isCancelled() {
        return CashbackStatus.CANCELLED.equals(status);
    }

    /**
     * Check if cashback is expired.
     */
    public boolean isExpired() {
        return CashbackStatus.EXPIRED.equals(status);
    }

    /**
     * Create a new cashback with updated status.
     * Used for state transitions (PENDING → CONFIRMED → PAID).
     *
     * @param newStatus New status
     * @param note Note for status change
     * @return New Cashback instance with updated status
     */
    public Cashback withStatus(CashbackStatus newStatus, String note) {
        LocalDateTime now = LocalDateTime.now();

        return Cashback.builder()
            .id(this.id)
            .userId(this.userId)
            .orderId(this.orderId)
            .orderItemId(this.orderItemId)
            .platformId(this.platformId)
            .commissionAmount(this.commissionAmount)
            .cashbackAmount(this.cashbackAmount)
            .cashbackRate(this.cashbackRate)
            .policyId(this.policyId)
            .status(newStatus)
            .note(note)
            .createdAt(this.createdAt)
            .confirmedAt(newStatus == CashbackStatus.CONFIRMED ? now : this.confirmedAt)
            .paidAt(newStatus == CashbackStatus.PAID ? now : this.paidAt)
            .cancelledAt(newStatus == CashbackStatus.CANCELLED ? now : this.cancelledAt)
            .updatedAt(now)
            .build();
    }
}
