package com.cashbee.domain.model;

import com.cashbee.domain.enums.PayoutMethod;
import com.cashbee.domain.enums.PayoutStatus;
import lombok.Builder;
import lombok.Getter;
import lombok.ToString;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * PayoutRequest Domain Model (Pure Domain Entity - NO JPA).
 *
 * Business Purpose:
 * Represents a user's request to withdraw (cash out) money from their wallet
 * to their bank account, Momo, or ZaloPay.
 *
 * Design:
 * - Immutable: Most fields are final (except mutable state fields)
 * - No JPA annotations: Pure domain model
 * - Self-validating: validate() method enforces business rules
 * - State transitions: approve(), reject(), complete(), cancel()
 *
 * Payout Lifecycle:
 * 1. REQUESTED → User creates payout request
 * 2. PROCESSING → Admin approves request
 * 3. PAID → System successfully transfers money
 * OR
 * 2. REJECTED → Admin rejects request
 * OR
 * 2. CANCELLED → User cancels before approval
 *
 * @author CashBee Team
 */
@Getter
@Builder
@ToString
public class PayoutRequest {

    /**
     * Payout request ID (generated by database).
     */
    private final Long id;

    /**
     * User who requested payout (FK to User).
     */
    private final Long userId;

    /**
     * Wallet to withdraw from (FK to UserWallet).
     */
    private final Long walletId;

    /**
     * Amount to withdraw (must be >= 50,000 VND).
     */
    private final BigDecimal amount;

    /**
     * Payout method (BANK, MOMO, ZALOPAY).
     */
    private final PayoutMethod payoutMethod;

    /**
     * Account number (bank account, phone number for Momo/ZaloPay).
     */
    private final String accountNumber;

    /**
     * Account holder name.
     */
    private final String accountName;

    /**
     * Bank name (required for BANK method, optional for others).
     */
    private final String bankName;

    /**
     * Current status of payout request.
     * Mutable because it changes through lifecycle.
     */
    private PayoutStatus status;

    /**
     * When payout was requested.
     */
    private final LocalDateTime requestedAt;

    /**
     * When payout was processed (approved/rejected).
     */
    private LocalDateTime processedAt;

    /**
     * Who processed the payout (admin ID or system).
     */
    private String processedBy;

    /**
     * When payout was completed (money transferred).
     */
    private LocalDateTime completedAt;

    /**
     * Reason for rejection/cancellation.
     */
    private String rejectionReason;

    /**
     * Minimum payout amount (50,000 VND).
     */
    public static final BigDecimal MINIMUM_PAYOUT_AMOUNT = new BigDecimal("50000.00");

    /**
     * Validates payout request business rules.
     *
     * Rules:
     * - userId must not be null
     * - walletId must not be null
     * - amount must be >= 50,000 VND
     * - payoutMethod must not be null
     * - accountNumber must not be null or blank
     * - accountName must not be null or blank
     * - status must not be null
     *
     * @throws IllegalArgumentException if validation fails
     */
    public void validate() {
        if (userId == null) {
            throw new IllegalArgumentException("PayoutRequest userId cannot be null");
        }

        if (walletId == null) {
            throw new IllegalArgumentException("PayoutRequest walletId cannot be null");
        }

        if (amount == null) {
            throw new IllegalArgumentException("PayoutRequest amount cannot be null");
        }

        if (amount.compareTo(BigDecimal.ZERO) <= 0) {
            throw new IllegalArgumentException(
                    "PayoutRequest amount must be greater than zero. Got: " + amount
            );
        }

        if (amount.compareTo(MINIMUM_PAYOUT_AMOUNT) < 0) {
            throw new IllegalArgumentException(
                    "PayoutRequest amount must be at least " + MINIMUM_PAYOUT_AMOUNT +
                            " (minimum payout). Got: " + amount
            );
        }

        if (payoutMethod == null) {
            throw new IllegalArgumentException("PayoutRequest payoutMethod cannot be null");
        }

        if (accountNumber == null || accountNumber.isBlank()) {
            throw new IllegalArgumentException("PayoutRequest accountNumber cannot be null or blank");
        }

        if (accountName == null || accountName.isBlank()) {
            throw new IllegalArgumentException("PayoutRequest accountName cannot be null or blank");
        }

        if (status == null) {
            throw new IllegalArgumentException("PayoutRequest status cannot be null");
        }
    }

    /**
     * Approves payout request.
     *
     * Transitions status from REQUESTED → PROCESSING.
     * Records who approved and when.
     *
     * @param adminId ID of admin who approved
     * @throws IllegalStateException if status is not REQUESTED
     */
    public void approve(String adminId) {
        if (status != PayoutStatus.REQUESTED) {
            throw new IllegalStateException(
                    "Can only approve payout with REQUESTED status. Current status: " + status
            );
        }

        this.status = PayoutStatus.PROCESSING;
        this.processedAt = LocalDateTime.now();
        this.processedBy = adminId;
    }

    /**
     * Approves payout request (without admin ID).
     * For backward compatibility and system-automated approvals.
     */
    public void approve() {
        approve("SYSTEM");
    }

    /**
     * Rejects payout request.
     *
     * Transitions status from REQUESTED → REJECTED.
     * Records reason, who rejected, and when.
     *
     * @param reason Reason for rejection
     * @param adminId ID of admin who rejected
     * @throws IllegalArgumentException if reason is null or blank
     * @throws IllegalStateException if status is not REQUESTED
     */
    public void reject(String reason, String adminId) {
        if (reason == null || reason.isBlank()) {
            throw new IllegalArgumentException("Rejection reason cannot be null or blank");
        }

        if (status != PayoutStatus.REQUESTED) {
            throw new IllegalStateException(
                    "Can only reject payout with REQUESTED status. Current status: " + status
            );
        }

        this.status = PayoutStatus.REJECTED;
        this.rejectionReason = reason;
        this.processedAt = LocalDateTime.now();
        this.processedBy = adminId;
    }

    /**
     * Rejects payout request (without admin ID).
     * For backward compatibility and system-automated rejections.
     */
    public void reject(String reason) {
        reject(reason, "SYSTEM");
    }

    /**
     * Completes payout (marks as PAID).
     *
     * Transitions status from PROCESSING → PAID.
     * Called after money is successfully transferred.
     *
     * @throws IllegalStateException if status is not PROCESSING
     */
    public void complete() {
        if (status != PayoutStatus.PROCESSING) {
            throw new IllegalStateException(
                    "Can only complete payout with PROCESSING status. Current status: " + status
            );
        }

        this.status = PayoutStatus.PAID;
        this.completedAt = LocalDateTime.now();
    }

    /**
     * Cancels payout request.
     *
     * Transitions status from REQUESTED → CANCELLED.
     * Usually initiated by user before admin processes.
     *
     * @param reason Reason for cancellation
     * @throws IllegalArgumentException if reason is null or blank
     * @throws IllegalStateException if status is not REQUESTED
     */
    public void cancel(String reason) {
        if (reason == null || reason.isBlank()) {
            throw new IllegalArgumentException("Cancellation reason cannot be null or blank");
        }

        if (status != PayoutStatus.REQUESTED) {
            throw new IllegalStateException(
                    "Can only cancel payout with REQUESTED status. Current status: " + status
            );
        }

        this.status = PayoutStatus.CANCELLED;
        this.rejectionReason = reason;
    }
}
