package com.cashbee.domain.model;

import com.cashbee.domain.enums.TransactionSourceType;
import com.cashbee.domain.enums.TransactionStatus;
import com.cashbee.domain.enums.TransactionType;
import lombok.Builder;
import lombok.Getter;
import lombok.ToString;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * Transaction Domain Model (Pure Domain Entity - NO JPA).
 *
 * Business Purpose:
 * Records all wallet operations for audit trail, history, and compliance.
 * Every wallet operation (pending add, confirm, lock, unlock, deduct) creates a transaction.
 *
 * Design:
 * - Immutable: All fields are final
 * - No JPA annotations: Pure domain model
 * - Self-validating: validate() method enforces business rules
 *
 * Transaction Types:
 * - CASHBACK: User earns cashback from affiliate orders
 * - WITHDRAW: User withdraws money
 * - BONUS: User receives bonus (e.g., sign-up bonus, referral bonus)
 * - REFERRAL: User receives referral commission
 * - REFUND: Money returned to user
 * - ADJUSTMENT: Manual adjustment by admin
 *
 * Transaction Statuses:
 * - SUCCESS: Transaction completed successfully
 * - PENDING: Transaction is being processed
 * - FAILED: Transaction failed
 * - CANCELLED: Transaction was cancelled
 *
 * @author CashBee Team
 */
@Getter
@Builder
@ToString
public class Transaction {

    /**
     * Transaction ID (generated by database).
     */
    private final Long id;

    /**
     * User who owns this transaction (FK to User).
     */
    private final Long userId;

    /**
     * Wallet affected by this transaction (FK to UserWallet).
     */
    private final Long walletId;

    /**
     * Type of transaction (CASHBACK, WITHDRAW, BONUS, etc.).
     */
    private final TransactionType type;

    /**
     * Transaction amount (always positive, direction determined by type).
     * Example:
     * - CASHBACK: +100.00 (adds to balance)
     * - WITHDRAW: +50.00 (represents 50 deducted, stored as positive)
     */
    private final BigDecimal amount;

    /**
     * Human-readable description of transaction.
     * Example: "Cashback from Shopee order #12345"
     */
    private final String description;

    /**
     * Balance before transaction was applied.
     */
    private final BigDecimal balanceBefore;

    /**
     * Balance after transaction was applied.
     */
    private final BigDecimal balanceAfter;

    /**
     * Transaction status (SUCCESS, PENDING, FAILED, CANCELLED).
     */
    private final TransactionStatus status;

    /**
     * Source type indicating where this transaction originated from.
     * Examples: ORDER (cashback), MILESTONE_BONUS, REFERRER_BONUS, PAYOUT, etc.
     */
    private final TransactionSourceType sourceType;

    /**
     * ID of the source record (FK to related table based on sourceType).
     * Examples:
     * - ORDER: cashback.id
     * - MILESTONE_BONUS: referral_reward.id
     * - REFERRER_BONUS: referral_reward.id
     * - REFERRER_COMMISSION: referrer_commission.id
     * - PAYOUT: payout_request.id or batch_transfer_item.id
     */
    private final Long sourceId;

    /**
     * When transaction was created.
     */
    private final LocalDateTime createdAt;

    /**
     * Validates transaction business rules.
     *
     * Rules:
     * - userId must not be null
     * - walletId must not be null
     * - type must not be null
     * - amount must be positive (> 0)
     * - balanceBefore must not be null
     * - balanceAfter must not be null
     * - status must not be null
     *
     * @throws IllegalArgumentException if validation fails
     */
    public void validate() {
        if (userId == null) {
            throw new IllegalArgumentException("Transaction userId cannot be null");
        }

        if (walletId == null) {
            throw new IllegalArgumentException("Transaction walletId cannot be null");
        }

        if (type == null) {
            throw new IllegalArgumentException("Transaction type cannot be null");
        }

        if (amount == null) {
            throw new IllegalArgumentException("Transaction amount cannot be null");
        }

        if (amount.compareTo(BigDecimal.ZERO) <= 0) {
            throw new IllegalArgumentException(
                    "Transaction amount must be greater than zero. Got: " + amount
            );
        }

        if (balanceBefore == null) {
            throw new IllegalArgumentException("Transaction balanceBefore cannot be null");
        }

        if (balanceAfter == null) {
            throw new IllegalArgumentException("Transaction balanceAfter cannot be null");
        }

        if (status == null) {
            throw new IllegalArgumentException("Transaction status cannot be null");
        }
    }
}
