package com.cashbee.domain.repository;

import com.cashbee.domain.enums.ReferrerCommissionStatus;
import com.cashbee.domain.model.ReferrerCommission;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

/**
 * ReferrerCommission Repository Interface (Port).
 *
 * <p>This is a domain interface that defines the contract for referrer commission persistence.
 * The infrastructure layer will provide the actual implementation.
 *
 * <p>Following Hexagonal Architecture principles:
 * <ul>
 *   <li>Domain layer defines WHAT operations are needed</li>
 *   <li>Infrastructure layer implements HOW (JPA, etc.)</li>
 * </ul>
 *
 * @author CashBee Team
 */
public interface ReferrerCommissionRepository {

    /**
     * Save a referrer commission (insert or update).
     *
     * @param commission ReferrerCommission to save
     * @return Saved commission with generated ID if new
     */
    ReferrerCommission save(ReferrerCommission commission);

    /**
     * Find referrer commission by ID.
     *
     * @param id Commission ID
     * @return Optional containing commission if found
     */
    Optional<ReferrerCommission> findById(Long id);

    /**
     * Find all commissions for a referrer.
     *
     * @param referrerId Referrer user ID
     * @return List of commissions for the referrer
     */
    List<ReferrerCommission> findByReferrerId(Long referrerId);

    /**
     * Find all commissions for a referrer by status.
     *
     * @param referrerId Referrer user ID
     * @param status     Commission status
     * @return List of commissions matching criteria
     */
    List<ReferrerCommission> findByReferrerIdAndStatus(Long referrerId, ReferrerCommissionStatus status);

    /**
     * Find all commissions from a specific referee.
     *
     * @param refereeId Referee user ID
     * @return List of commissions generated by the referee
     */
    List<ReferrerCommission> findByRefereeId(Long refereeId);

    /**
     * Find commission by source order ID.
     *
     * @param sourceOrderId Order ID
     * @return Optional containing commission if found
     */
    Optional<ReferrerCommission> findBySourceOrderId(Long sourceOrderId);

    /**
     * Check if commission exists for a specific order.
     * Used to prevent duplicate commissions.
     *
     * @param sourceOrderId Order ID
     * @return true if commission already exists
     */
    boolean existsBySourceOrderId(Long sourceOrderId);

    /**
     * Find all commissions by status.
     *
     * @param status Commission status
     * @return List of commissions with given status
     */
    List<ReferrerCommission> findByStatus(ReferrerCommissionStatus status);

    /**
     * Find all expired commissions that are still pending.
     *
     * @param now Current timestamp
     * @return List of expired pending commissions
     */
    List<ReferrerCommission> findExpiredPendingCommissions(LocalDateTime now);

    /**
     * Sum total commission amount for a referrer.
     *
     * @param referrerId Referrer user ID
     * @return Total commission amount (all statuses)
     */
    BigDecimal sumCommissionByReferrerId(Long referrerId);

    /**
     * Sum pending commission amount for a referrer.
     *
     * @param referrerId Referrer user ID
     * @return Total pending commission amount
     */
    BigDecimal sumPendingCommissionByReferrerId(Long referrerId);

    /**
     * Sum confirmed commission amount for a referrer.
     *
     * @param referrerId Referrer user ID
     * @return Total confirmed (not yet paid) commission amount
     */
    BigDecimal sumConfirmedCommissionByReferrerId(Long referrerId);

    /**
     * Sum paid commission amount for a referrer.
     *
     * @param referrerId Referrer user ID
     * @return Total paid commission amount
     */
    BigDecimal sumPaidCommissionByReferrerId(Long referrerId);

    /**
     * Count commissions by referrer ID.
     *
     * @param referrerId Referrer user ID
     * @return Number of commissions for the referrer
     */
    long countByReferrerId(Long referrerId);

    /**
     * Count commissions by referee ID.
     *
     * @param refereeId Referee user ID
     * @return Number of commissions from the referee
     */
    long countByRefereeId(Long refereeId);

    /**
     * Find commissions between referrer and referee.
     *
     * @param referrerId Referrer user ID
     * @param refereeId  Referee user ID
     * @return List of commissions between the two users
     */
    List<ReferrerCommission> findByReferrerIdAndRefereeId(Long referrerId, Long refereeId);

    /**
     * Find all UNPAID (CONFIRMED but not yet transferred in batch) commissions for a referrer.
     * Unpaid means: status=CONFIRMED/PAID AND paidBatchId IS NULL
     *
     * @param referrerId Referrer user ID
     * @return List of unpaid commissions
     */
    List<ReferrerCommission> findUnpaidByReferrerId(Long referrerId);

    /**
     * Sum the total unpaid commission amount for a referrer.
     * Used to include commission in batch transfer calculation.
     *
     * @param referrerId Referrer user ID
     * @return Total unpaid commission amount (or 0 if none)
     */
    BigDecimal sumUnpaidCommissionByReferrerId(Long referrerId);

    /**
     * Mark commissions as paid by a batch.
     * Sets paidBatchId and paidAt for the given commission IDs.
     *
     * @param commissionIds List of commission IDs to mark as paid
     * @param batchId       Batch ID that paid these commissions
     * @return Number of commissions updated
     */
    int markAsPaidByBatch(List<Long> commissionIds, Long batchId);

    /**
     * Find all commissions paid by a specific batch for a specific referrer.
     * Used for invoice detail to show referrer commission breakdown.
     *
     * @param batchId    Batch ID
     * @param referrerId Referrer user ID
     * @return List of commissions paid by the batch for the referrer
     */
    List<ReferrerCommission> findByPaidBatchIdAndReferrerId(Long batchId, Long referrerId);
}
